import type { Metadata } from "next";

import "./globals.css";
import ModalNewTask from "@/components/ModalNewTask";

export const metadata: Metadata = {
  title: "TaskStar AI",
  description: "Generated by Thais Jacob Lannes",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <ModalNewTask />
      </body>
    </html>
  );
}
